postgres-dwh:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'localhost') }}"
      port: "{{ env_var('POSTGRES_PORT', 5434) | int }}"
      user: "{{ env_var('POSTGRES_USER', 'dwh_user') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'dwh_pass') }}"
      dbname: "{{ env_var('POSTGRES_DB', 'dwh') }}"
      schema: dwh_main_dev
      threads: 4