name: 'olist_dbt'
version: '1.0.0'
config-version: 2

profile: 'olist_project'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
snapshot-paths: ["snapshots"]
analysis-paths: ["analyses"]
target-path: "target"

clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

seeds:
  olist_dbt:
    +tags: "lookup"

models:
  olist_dbt:
    +materialized: view
    
    staging:
      +materialized: table
      +tags: "staging"
      stg__orders:
        +materialized: incremental
        +unique_key: order_id
      
      stg__order_items:
        +materialized: incremental
      
      stg__payments:
        +materialized: incremental
      
      stg__reviews:
        +materialized: incremental
        +unique_key: review_id

    marts:
      +materialized: table
      dimensions:
        +tags: "dimension"
      facts:
        +tags: "fact"
      lookups:
        +tags: ["dimension", "lookup"]
