name: 'olist_dbt'
version: '1.0.0'
config-version: 2

profile: 'olist_project'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
snapshot-paths: ["snapshots"]
analysis-paths: ["analyses"]
target-path: "target"

clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

seeds:
  olist_dbt:
    +tags: "lookup"

models:
  olist_dbt:
    # By default, everything in the project is a view (safe)
    +materialized: view
    
    staging:
      # 1. Default strategy for the entire 'staging' folder is TABLE.
      # This ensures products, sellers, geo will be fast but always fresh (Full Refresh).
      +materialized: table
      +tags: "staging"

      # 2. Exceptions for specific models (Big Four)
      # Here we override the 'table' setting to 'incremental'
      stg__orders:
        +materialized: incremental
        +unique_key: order_id
      
      stg__order_items:
        +materialized: incremental
        # Note: order_items does not have a single ID, the key is a pair.
        # In Postgres, dbt incremental without unique_key acts as "append-only" (appends).
        # If you want updates, you must define a composite key (but that's harder).
        # For now, 'append' is enough if data doesn't change retroactively.
      
      stg__payments:
        +materialized: incremental
      
      stg__reviews:
        +materialized: incremental
        +unique_key: review_id

    marts:
      +materialized: table
      dimensions:
        +tags: "dimension"
      facts:
        +tags: "fact"
      lookups:
        +tags: ["dimension", "lookup"]