olist_project:
  target: local

  outputs:
    local:
      type: postgres
      threads: 1
      host: "{{ env_var('DWH_POSTGRES_HOST', 'localhost') }}"
      port: "{{ env_var('DWH_POSTGRES_PORT', '5434') | int }}"
      user: "{{ env_var('POSTGRES_USER', 'dwh_user') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'dwh_pass') }}"
      dbname: "{{ env_var('POSTGRES_DB', 'dwh') }}"
      schema: dwh_main_dev  

    docker:
      type: postgres
      threads: 4
      host: "{{ env_var('DWH_POSTGRES_DOCKER_HOST', 'postgres-dwh') }}"
      port: "{{ env_var('DWH_POSTGRES_DOCKER_PORT', '5432') | int }}"
      user: "{{ env_var('POSTGRES_USER', 'dwh_user') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'dwh_pass') }}"
      dbname: "{{ env_var('POSTGRES_DB', 'dwh') }}"

      schema: main
