olist_project:
  target: local

  outputs:
    local:
      type: postgres
      threads: 1
      host: localhost
      port: 5434            
      user: olist
      password: olist       
      dbname: olist_dwh
      schema: dwh_main_dev  

    docker:
      type: postgres
      threads: 4
      host: postgres-dwh  
      port: 5432            

      user: "{{ env_var('POSTGRES_USER', 'olist') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'olist') }}" 
      dbname: "{{ env_var('POSTGRES_DB', 'olist_dwh') }}"

      schema: dwh_main_prod